### ISSUE TITLE
All devices are not scanning

### ISSUE THREAD

**Issue by chanchal1987** [cisasteelersfan/xfinity_gateway#4]
Not displaying more than 15 devices. Most probably login feature is needed to scan all devices.

![869331432](https://user-images.githubusercontent.com/284846/69396415-03b4d880-0c97-11ea-9058-94ae8d5a6306.png)

**Comment by cisasteelersfan** [comment]
You are absolutely right. Unfortunately I no longer have Xfinity service nor do I own their modem anymore. If you or someone else is interested, I could transfer ownership of the Pypi repository so that someone could continue on with the project.
